server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/testat
  datasource:
    url: jdbc:h2:mem:at
    username: sa
    password: p
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: at
